### ISSUE TITLE
Audio is cut every 2 seconds using twitchpipe -a username > recording.ts

### ISSUE THREAD

**Issue by jedai47** [Hakkin/twitchpipe#21]
video is fine, anyone having the same issue ?

**Comment by Hakkin** [comment]
Are there any errors reported in the console? Audio and video are both packaged into the same files for Twitch, so it would be odd if one is working but the other isn't. It may be caused by the media player you're using, especially if the recording includes ads (or a "commercial break" screen), this causes a discontinuity in the video data which some players don't handle well. I've been meaning to add an option to filter out ads/commercials from the output, but haven't gotten around to it yet unfortunately. For now the only thing I could suggest is try a different media player, or maybe try running the recording through ffmpeg first to "fix" it (`ffmpeg -i recording.ts -c copy recording_fixed.ts`). I can't guarantee this would fix it, but it might.

**Comment by jedai47** [comment]
well im using VLC and yeah the first thing that poped up was a commercial break, will try the ffmpeg fix and tell u what it is about

**Comment by jedai47** [comment]
alright i decided just to retry it and this time since i guess the commercial break didnt pop up, i didnt get the audio cuts. Closing for now ?

**Comment by Hakkin** [comment]
I was able to confirm this behavior with VLC, it seems you can fix it by disabling then enabling the audio track again once the commercial screen ends.

**Comment by jedai47** [comment]
works like a charm <3
